# Generated by Django 4.1.6 on 2023-03-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='Customer',
            name='phone',
            field=models.IntegerField(blank = False, null=True),
        ),
    ]
