# Generated by Django 4.1.6 on 2023-03-13 13:35

from django.db import migrations


def assign_phone(apps, schema_editor):
    Customer = apps.get_model('core', 'Customer')
    for customer in Customer.objects.all():
        customer.phone = 65586775
        customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_phone'),
    ]

    operations = [
        migrations.RunPython(assign_phone)
    ]
