# Generated by Django 4.1.6 on 2023-03-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customer_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='date_enrolled',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
