# Generated by Django 4.1.6 on 2023-03-16 10:51
from django.db import migrations

def assign_customer_perms(apps, schema_editor):
    
    # fetch the models
    Permission = apps.get_model('auth','Permission')
    Group = apps.get_model('auth', 'Group')

    # create Permission
    perms = Permission.objects
    customer_perms = [
        perms.get(codename='add_order'),
        perms.get(codename='view_order'),
        perms.get(codename='change_order'),
        perms.get(codename='delete_order'),

        perms.get(codename='add_orderitem'),
        perms.get(codename='view_orderitem'),
        perms.get(codename='change_orderitem'),
        perms.get(codename='delete_orderitem'),

        perms.get(codename='add_reservation'),
        perms.get(codename='view_reservation'),
        perms.get(codename='change_reservation'),
        perms.get(codename='delete_reservation'),
    
        perms.get(codename='view_item'),
        perms.get(codename='view_payment'),
        perms.get(codename='add_payment')
    ]

    # create Group and assign perms
    admin = Group.objects.create(name = 'admin')
    admin.save()
    customer = Group.objects.create(name = 'customer')
    customer.permissions.set(customer_perms)
    customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ChangeCustomer'),
    ]

    operations = [
        migrations.RunPython(assign_customer_perms)
    ]
