# Generated by Django 4.1.6 on 2023-03-16 10:51
from django.db import migrations, 

def assign_customer_perms(apps, schema_editor):
    
    # fetch the models
    Permissions = apps.get_model('auth','Permissions')
    Groups = apps.get_model('auth', 'Groups')
    
    # create groups
    admin = Groups.objects.create(name = 'admin')
    admin.save()
    customer = Groups.objects.create(name = 'customer')
    customer.save()

    # create permissions
    perms = Permissions.objects
    customer_perms = [
        perms.get(codename='core.add_Order'),
        perms.get(codename='core.view_Order'),
        perms.get(codename='core.change_Order'),
        perms.get(codename='core.order_Order'),

        perms.get(codename='core.add_OrderItem')
        perms.get(codename='core.view_OrderItem')
        perms.get(codename='core.change_OrderItem')
        perms.get(codename='core.delete_OrderItem')

        perms.get(codename='core.add_Reservation')
        perms.get(codename='core.view_Reservation')
        perms.get(codename='core.change_Reservation')
        perms.get(codename='core.delete_Reservation')
    
        perms.get(codename='core.view_Item')
        perms.get(codename='core.view_Payment')
        perms.get(codename='core.add_Payment')
    ]

    # assign perms
    customer.permissions.set(customer_perms)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ChangeCustomer'),
    ]

    operations = [
        migrations.RunPython(assign_customer_perms)
    ]
