# Generated by Django 4.1.6 on 2023-03-16 10:51
from django.db import migrations

def assign_customer_perms(apps, schema_editor):
    
    # fetch the models
    Permission = apps.get_model('auth','Permission')
    Group = apps.get_model('auth', 'Group')

    # create Permission
    customer_perms = [
        #Order model permission codenames
        'add_order',
        'view_order',
        'change_order',
        'delete_order',
        #OrderItem model permission codenames
        'add_orderitem',
        'view_orderitem',
        'change_orderitem',
        'delete_orderitem',
        #Reservation model permission codenames
        'add_reservation',
        'view_reservation',
        'change_reservation',
        'delete_reservation',
        #Item and Payment model permission codenames
        'view_item',
        'view_payment',
        'add_payment'
    ]

    # create Group and assign perms
    admin = Group.objects.create(name = 'admin')
    admin.save()
    customer = Group.objects.create(name = 'customer')
    customer.permissions.set([perm for perm in Permission.objects.all() if perm.codename in customer_perms])
    customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_ChangeCustomer',)
    ]

    operations = [
        migrations.RunPython(assign_customer_perms)
    ]
